spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    example: mongoT.ReglasGestorCodigos.CatalogoReglasKCPruebas

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.asierg: DEBUG